### ISSUE TITLE
Remove calls to listNodePubKeys

### ISSUE THREAD

**Issue by brh28** [lnflash/flash#60]
In Honeycomb, currently seeing errors with:
```
name: "OffChainServiceUnavailableError"
message: "no active lightning node (for offchain)"
stacktrace: "OffChainServiceUnavailableError: no active lightning node (for offchain)
    at getActiveLnd (/app/lib/services/lnd/config.js:23:16)
    at LndService (/app/lib/services/lnd/index.js:24:50)
    at listNodesPubkeys (/app/lib/app/lightning/list-nodes-pubkeys.js:6:50)
    at /app/lib/services/tracing.js:335:35
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at AsyncLocalStorageContextManager.with (/app/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at ContextAPI.with (/app/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at Tracer.startActiveSpan (/app/node_modules/@opentelemetry/sdk-trace-base/build/src/Tracer.js:122:32)
    at Object.listNodesPubkeys (/app/lib/services/tracing.js:333:36)
    at resolve (/app/lib/graphql/public/root/query/globals.js:15:47)"
``` 
Here's a sample trace: https://ui.honeycomb.io/island-bitcoin/environments/test/result/fSnzYzahs98/trace/9NgzRvvvD5B?fields[]=s_name&fields[]=s_serviceName&span=bba4c00091cd1555

We want to remove this call because it adds noise to Honeycomb and we don't know if there are possible adverse effects.

**Comment by brh28** [comment]
Reproduce with following GQL query:
```query scanningQRCodeScreen__public__0{globals{__typename network}me{__typename id defaultAccount{__typename id wallets{__typename id}}contacts{__typename id username}}}```
